title: Swapnil Tayde
logo: docs/assets/Swapnil-Tayde-Logo.png
description: Curious, Disciplined, Driven Data Learner who wants to help in turning raw data into actionable insights.
#show_downloads: true
theme: jekyll-theme-minimal
